# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Publish PowerShell Module
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Configure GitHub package registry source
        run: dotnet nuget add source --username Smalls1652 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Smalls1652/index.json"

      - name: Run 'dotnet restore'
        run: dotnet restore "SmallsOnline.Subnetting.Pwsh.sln"

      - name: Run MSBuild
        run: dotnet msbuild "SmallsOnline.Subnetting.Pwsh.sln" -target:"Restore;Clean;Build;Publish;BuildModuleDir" -property:"Configuration=Release;DebugType=none;DebugSymbols=false"

      - name: Publish PowerShell Module
        uses: pwsh
        run: |
          Publish-Module -Path "./build/SmallsOnline.Subnetting.Pwsh/" -NuGetApiKey "${{ secrets.PWSH_GALLERY_KEY }}" -Repository "PSGallery" -Verbose